name: dart_repro

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  build_runner: any
  build_web_compilers: any

dependency_overrides:
  build_web_compilers:
    git:
      url: git@github.com:dart-lang/build.git
      path: build_web_compilers
  build_modules:
    git:
      url: git@github.com:dart-lang/build.git
      path: build_modules
